CREATE TABLE IF NOT EXISTS `notice_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `email` VARCHAR(120) NULL ,
  `email_sent` BOOLEAN NOT NULL DEFAULT 0,
  `phone` VARCHAR(20) NULL ,
  `phone_sent` BOOLEAN NOT NULL DEFAULT 0,
  `version` VARCHAR(20) NULL ,
  `create_time` TIMESTAMP NOT NULL,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
